version = "1.26.*"
upstream_repository = "https://github.com/urllib3/urllib3"
obsolete_since = "2.0.0" # Released on 2023-04-26
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
extras = ["socks"]
