from _typeshed import Incomplete

def degree_assortativity_coefficient(
    G, x: str = "out", y: str = "in", weight: Incomplete | None = None, nodes: Incomplete | None = None
): ...
def degree_pearson_correlation_coefficient(
    G, x: str = "out", y: str = "in", weight: Incomplete | None = None, nodes: Incomplete | None = None
): ...
def attribute_assortativity_coefficient(G, attribute, nodes: Incomplete | None = None): ...
def numeric_assortativity_coefficient(G, attribute, nodes: Incomplete | None = None): ...
