from _typeshed import Incomplete

class VolumeApiMixin:
    def volumes(self, filters: Incomplete | None = None): ...
    def create_volume(
        self,
        name: Incomplete | None = None,
        driver: Incomplete | None = None,
        driver_opts: Incomplete | None = None,
        labels: Incomplete | None = None,
    ): ...
    def inspect_volume(self, name): ...
    def prune_volumes(self, filters: Incomplete | None = None): ...
    def remove_volume(self, name, force: bool = False) -> None: ...
