from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def core_number(G): ...
@_dispatchable
def k_core(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
@_dispatchable
def k_shell(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
@_dispatchable
def k_crust(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
@_dispatchable
def k_corona(G, k, core_number: Incomplete | None = None): ...
@_dispatchable
def k_truss(G, k): ...
@_dispatchable
def onion_layers(G): ...
