from _typeshed import Incomplete
from collections.abc import Generator

def cycle_basis(G, root: Incomplete | None = None): ...
def simple_cycles(G, length_bound: Incomplete | None = None) -> Generator[Incomplete, Incomplete, None]: ...

class _NeighborhoodCache(dict[Incomplete, Incomplete]):
    G: Incomplete
    def __init__(self, G) -> None: ...
    def __missing__(self, v): ...

def chordless_cycles(G, length_bound: Incomplete | None = None) -> Generator[Incomplete, Incomplete, None]: ...
def recursive_simple_cycles(G): ...
def find_cycle(G, source: Incomplete | None = None, orientation: Incomplete | None = None): ...
def minimum_cycle_basis(G, weight: Incomplete | None = None): ...
