from networkx.classes.graph import Graph, _Node
from networkx.utils.backends import _dispatchable

@_dispatchable
def is_distance_regular(G: Graph[_Node]): ...
@_dispatchable
def global_parameters(b, c): ...
@_dispatchable
def intersection_array(G: Graph[_Node]): ...
@_dispatchable
def is_strongly_regular(G: Graph[_Node]): ...
