from networkx.utils.backends import _dispatchable

@_dispatchable
def is_distance_regular(G): ...
@_dispatchable
def global_parameters(b, c): ...
@_dispatchable
def intersection_array(G): ...
@_dispatchable
def is_strongly_regular(G): ...
