from networkx.utils.backends import _dispatchable

@_dispatchable
def maximal_matching(G): ...
@_dispatchable
def is_matching(G, matching): ...
@_dispatchable
def is_maximal_matching(G, matching): ...
@_dispatchable
def is_perfect_matching(G, matching): ...
@_dispatchable
def min_weight_matching(G, weight: str = "weight"): ...
@_dispatchable
def max_weight_matching(G, maxcardinality: bool = False, weight: str = "weight"): ...
