from _typeshed import Incomplete

def random_reference(G, niter: int = 1, connectivity: bool = True, seed: Incomplete | None = None): ...
def lattice_reference(
    G, niter: int = 5, D: Incomplete | None = None, connectivity: bool = True, seed: Incomplete | None = None
): ...
def sigma(G, niter: int = 100, nrand: int = 10, seed: Incomplete | None = None): ...
def omega(G, niter: int = 5, nrand: int = 10, seed: Incomplete | None = None): ...
