from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def is_tournament(G): ...
@_dispatchable
def hamiltonian_path(G): ...
@_dispatchable
def random_tournament(n, seed: Incomplete | None = None): ...
@_dispatchable
def score_sequence(G): ...
@_dispatchable
def is_reachable(G, s, t): ...
@_dispatchable
def is_strongly_connected(G): ...
