version = "0.13.2"
# Requires a version of numpy and matplotlib with a `py.typed` file
# see https://github.com/python/typeshed/issues/12551
# on why we need the upper bound for numpy
requires = ["matplotlib>=3.8", "numpy>=1.20,<2.1.0", "pandas-stubs"]
# matplotlib>=3.8 requires Python >=3.9
requires_python = ">=3.9"
upstream_repository = "https://github.com/mwaskom/seaborn"
