__all__ = ["load_taiga_fontanka_metas", "load_taiga_fontanka"]

def load_taiga_fontanka_metas(path, offset: int = 0, count=13): ...
def load_taiga_fontanka(path, metas=None, offset: int = 306359296, count: int = 342683): ...
