from typing import Any

EPSILON: float

def linear(middle, pos): ...
def curved(middle, pos): ...
def sine(middle, pos): ...
def sphere_increasing(middle, pos): ...
def sphere_decreasing(middle, pos): ...

SEGMENTS: Any

class GradientFile:
    gradient: Any
    def getpalette(self, entries: int = 256): ...

class GimpGradientFile(GradientFile):
    gradient: Any
    def __init__(self, fp) -> None: ...
