from typing import Any

def constant(image, value): ...
def duplicate(image): ...
def invert(image): ...
def lighter(image1, image2): ...
def darker(image1, image2): ...
def difference(image1, image2): ...
def multiply(image1, image2): ...
def screen(image1, image2): ...
def soft_light(image1, image2): ...
def hard_light(image1, image2): ...
def overlay(image1, image2): ...
def add(image1, image2, scale: float = ..., offset: int = ...): ...
def subtract(image1, image2, scale: float = ..., offset: int = ...): ...
def add_modulo(image1, image2): ...
def subtract_modulo(image1, image2): ...
def logical_and(image1, image2): ...
def logical_or(image1, image2): ...
def logical_xor(image1, image2): ...
def blend(image1, image2, alpha): ...
def composite(image1, image2, mask): ...
def offset(image, xoffset, yoffset: Any | None = ...): ...
