from typing import Any

QImage = Any  # imported from either of {PyQt6,PySide6,PyQt5,PySide2}.QtGui

qt_versions: Any
qt_is_installed: bool
qt_version: Any

def rgb(r, g, b, a: int = ...): ...
def fromqimage(im): ...
def fromqpixmap(im): ...
def align8to32(bytes, width, mode): ...

class ImageQt(QImage):  # type: ignore
    def __init__(self, im) -> None: ...

def toqimage(im): ...
def toqpixmap(im): ...
