from typing import Any

LUT_SIZE: Any
ROTATION_MATRIX: Any
MIRROR_MATRIX: Any

class LutBuilder:
    patterns: Any
    lut: Any
    def __init__(self, patterns: Any | None = ..., op_name: Any | None = ...) -> None: ...
    def add_patterns(self, patterns) -> None: ...
    def build_default_lut(self) -> None: ...
    def get_lut(self): ...
    def build_lut(self): ...

class MorphOp:
    lut: Any
    def __init__(self, lut: Any | None = ..., op_name: Any | None = ..., patterns: Any | None = ...) -> None: ...
    def apply(self, image): ...
    def match(self, image): ...
    def get_on_pixels(self, image): ...
    def load_lut(self, filename) -> None: ...
    def save_lut(self, filename) -> None: ...
    def set_lut(self, lut) -> None: ...
