def min_cost_flow_cost(G, demand: str = "demand", capacity: str = "capacity", weight: str = "weight"): ...
def min_cost_flow(G, demand: str = "demand", capacity: str = "capacity", weight: str = "weight"): ...
def cost_of_flow(G, flowDict, weight: str = "weight"): ...
def max_flow_min_cost(G, s, t, capacity: str = "capacity", weight: str = "weight"): ...
