from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def from_sparse6_bytes(string): ...
def to_sparse6_bytes(G, nodes: Incomplete | None = None, header: bool = True): ...
@_dispatchable
def read_sparse6(path): ...
def write_sparse6(G, path, nodes: Incomplete | None = None, header: bool = True) -> None: ...
