version = "3.0.1"
upstream_repository = "https://github.com/nickmaccarthy/python-datemath"
# Requires a version of arrow with a `py.typed` file
requires = ["arrow>=1.0.1"]
obsolete_since = "3.0.2"    # Released on 2024-09-11

[tool.stubtest]
ignore_missing_stub = true
