version = "1.15.*"
upstream_repository = "https://github.com/libgit2/pygit2"
requires = ["types-cffi"]
obsolete_since = "1.16.0" # Released on 2024-10-11

[tool.stubtest]
platforms = ["darwin", "linux", "win32"]
