def tensor_product(G, H): ...
def cartesian_product(G, H): ...
def lexicographic_product(G, H): ...
def strong_product(G, H): ...
def power(G, k): ...
def rooted_product(G, H, root): ...
def corona_product(G, H): ...
