from ..scope_manager import ScopeManager
from ..span import Span
from ..tracer import Tracer
from .propagator import Propagator

class MockTracer(Tracer):
    def __init__(self, scope_manager: ScopeManager | None = ...) -> None: ...
    def register_propagator(self, format: str, propagator: Propagator) -> None: ...
    def finished_spans(self) -> list[Span]: ...
    def reset(self) -> None: ...
