# Standard pnpm install using the public npm registry.

name: pnpm install (public registry)
description: Install the pnpm workspace from the public npm registry.

inputs:
  working-directory:
    description: Directory in which to run pnpm install
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Standard pnpm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
      run: pnpm run install:all
