# Standard npm install using the public npm registry.

name: npm install (public registry)

on:
  workflow_call:

runs:
  using: composite
  steps:
    - uses: ./.github/actions/npm-cache-dir

    - name: Standard npm install
      shell: bash
      run: npm run install:all
