class DecimalResultProcessor:
    def __init__(self, *args, **kwargs) -> None: ...
    def process(self, *args, **kwargs): ...

class UnicodeResultProcessor:
    def __init__(self, *args, **kwargs) -> None: ...
    def conditional_process(self, *args, **kwargs): ...
    def process(self, *args, **kwargs): ...

def int_to_boolean(*args, **kwargs): ...
def str_to_date(*args, **kwargs): ...
def str_to_datetime(*args, **kwargs): ...
def str_to_time(*args, **kwargs): ...
def to_float(*args, **kwargs): ...
def to_str(*args, **kwargs): ...
