from _typeshed import Incomplete

from influxdb_client.domain.view_properties import ViewProperties

class CheckViewProperties(ViewProperties):
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        type: Incomplete | None = ...,
        shape: Incomplete | None = ...,
        check_id: Incomplete | None = ...,
        check: Incomplete | None = ...,
        queries: Incomplete | None = ...,
        colors: Incomplete | None = ...,
        legend_colorize_rows: Incomplete | None = ...,
        legend_hide: Incomplete | None = ...,
        legend_opacity: Incomplete | None = ...,
        legend_orientation_threshold: Incomplete | None = ...,
    ) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def shape(self): ...
    @shape.setter
    def shape(self, shape) -> None: ...
    @property
    def check_id(self): ...
    @check_id.setter
    def check_id(self, check_id) -> None: ...
    @property
    def check(self): ...
    @check.setter
    def check(self, check) -> None: ...
    @property
    def queries(self): ...
    @queries.setter
    def queries(self, queries) -> None: ...
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, colors) -> None: ...
    @property
    def legend_colorize_rows(self): ...
    @legend_colorize_rows.setter
    def legend_colorize_rows(self, legend_colorize_rows) -> None: ...
    @property
    def legend_hide(self): ...
    @legend_hide.setter
    def legend_hide(self, legend_hide) -> None: ...
    @property
    def legend_opacity(self): ...
    @legend_opacity.setter
    def legend_opacity(self, legend_opacity) -> None: ...
    @property
    def legend_orientation_threshold(self): ...
    @legend_orientation_threshold.setter
    def legend_orientation_threshold(self, legend_orientation_threshold) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
