from _typeshed import Incomplete

from influxdb_client.domain.scraper_target_request import ScraperTargetRequest

class ScraperTargetResponse(ScraperTargetRequest):
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        id: Incomplete | None = ...,
        org: Incomplete | None = ...,
        bucket: Incomplete | None = ...,
        links: Incomplete | None = ...,
        name: Incomplete | None = ...,
        type: Incomplete | None = ...,
        url: Incomplete | None = ...,
        org_id: Incomplete | None = ...,
        bucket_id: Incomplete | None = ...,
        allow_insecure: bool = ...,
    ) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def org(self): ...
    @org.setter
    def org(self, org) -> None: ...
    @property
    def bucket(self): ...
    @bucket.setter
    def bucket(self, bucket) -> None: ...
    @property
    def links(self): ...
    @links.setter
    def links(self, links) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
