from _typeshed import Incomplete

from influxdb_client.domain.telegraf_request import TelegrafRequest

class Telegraf(TelegrafRequest):
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        id: Incomplete | None = ...,
        links: Incomplete | None = ...,
        labels: Incomplete | None = ...,
        name: Incomplete | None = ...,
        description: Incomplete | None = ...,
        metadata: Incomplete | None = ...,
        config: Incomplete | None = ...,
        org_id: Incomplete | None = ...,
    ) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def links(self): ...
    @links.setter
    def links(self, links) -> None: ...
    @property
    def labels(self): ...
    @labels.setter
    def labels(self, labels) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
