"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class FileDescriptorSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FILE_FIELD_NUMBER: builtins.int

    @property
    def file(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FileDescriptorProto]: ...

    def __init__(self,
        *,
        file : typing.Optional[typing.Iterable[global___FileDescriptorProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"file",b"file"]) -> None: ...
global___FileDescriptorSet = FileDescriptorSet

class FileDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    PACKAGE_FIELD_NUMBER: builtins.int
    DEPENDENCY_FIELD_NUMBER: builtins.int
    PUBLIC_DEPENDENCY_FIELD_NUMBER: builtins.int
    WEAK_DEPENDENCY_FIELD_NUMBER: builtins.int
    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    ENUM_TYPE_FIELD_NUMBER: builtins.int
    SERVICE_FIELD_NUMBER: builtins.int
    EXTENSION_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    SOURCE_CODE_INFO_FIELD_NUMBER: builtins.int
    SYNTAX_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    package: typing.Text = ...

    @property
    def dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...

    @property
    def public_dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...

    @property
    def weak_dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    syntax: typing.Text = ...

    @property
    def message_type(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DescriptorProto]: ...

    @property
    def enum_type(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnumDescriptorProto]: ...

    @property
    def service(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceDescriptorProto]: ...

    @property
    def extension(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldDescriptorProto]: ...

    @property
    def options(self) -> global___FileOptions: ...

    @property
    def source_code_info(self) -> global___SourceCodeInfo: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        package : typing.Optional[typing.Text] = ...,
        dependency : typing.Optional[typing.Iterable[typing.Text]] = ...,
        public_dependency : typing.Optional[typing.Iterable[builtins.int]] = ...,
        weak_dependency : typing.Optional[typing.Iterable[builtins.int]] = ...,
        message_type : typing.Optional[typing.Iterable[global___DescriptorProto]] = ...,
        enum_type : typing.Optional[typing.Iterable[global___EnumDescriptorProto]] = ...,
        service : typing.Optional[typing.Iterable[global___ServiceDescriptorProto]] = ...,
        extension : typing.Optional[typing.Iterable[global___FieldDescriptorProto]] = ...,
        options : typing.Optional[global___FileOptions] = ...,
        source_code_info : typing.Optional[global___SourceCodeInfo] = ...,
        syntax : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options",u"package",b"package",u"source_code_info",b"source_code_info",u"syntax",b"syntax"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dependency",b"dependency",u"enum_type",b"enum_type",u"extension",b"extension",u"message_type",b"message_type",u"name",b"name",u"options",b"options",u"package",b"package",u"public_dependency",b"public_dependency",u"service",b"service",u"source_code_info",b"source_code_info",u"syntax",b"syntax",u"weak_dependency",b"weak_dependency"]) -> None: ...
global___FileDescriptorProto = FileDescriptorProto

class DescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class ExtensionRange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        OPTIONS_FIELD_NUMBER: builtins.int
        start: builtins.int = ...
        end: builtins.int = ...

        @property
        def options(self) -> global___ExtensionRangeOptions: ...

        def __init__(self,
            *,
            start : typing.Optional[builtins.int] = ...,
            end : typing.Optional[builtins.int] = ...,
            options : typing.Optional[global___ExtensionRangeOptions] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"end",b"end",u"options",b"options",u"start",b"start"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"end",b"end",u"options",b"options",u"start",b"start"]) -> None: ...

    class ReservedRange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        start: builtins.int = ...
        end: builtins.int = ...

        def __init__(self,
            *,
            start : typing.Optional[builtins.int] = ...,
            end : typing.Optional[builtins.int] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"end",b"end",u"start",b"start"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"end",b"end",u"start",b"start"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    EXTENSION_FIELD_NUMBER: builtins.int
    NESTED_TYPE_FIELD_NUMBER: builtins.int
    ENUM_TYPE_FIELD_NUMBER: builtins.int
    EXTENSION_RANGE_FIELD_NUMBER: builtins.int
    ONEOF_DECL_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    RESERVED_RANGE_FIELD_NUMBER: builtins.int
    RESERVED_NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def reserved_name(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...

    @property
    def field(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldDescriptorProto]: ...

    @property
    def extension(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldDescriptorProto]: ...

    @property
    def nested_type(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DescriptorProto]: ...

    @property
    def enum_type(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnumDescriptorProto]: ...

    @property
    def extension_range(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DescriptorProto.ExtensionRange]: ...

    @property
    def oneof_decl(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OneofDescriptorProto]: ...

    @property
    def options(self) -> global___MessageOptions: ...

    @property
    def reserved_range(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DescriptorProto.ReservedRange]: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        field : typing.Optional[typing.Iterable[global___FieldDescriptorProto]] = ...,
        extension : typing.Optional[typing.Iterable[global___FieldDescriptorProto]] = ...,
        nested_type : typing.Optional[typing.Iterable[global___DescriptorProto]] = ...,
        enum_type : typing.Optional[typing.Iterable[global___EnumDescriptorProto]] = ...,
        extension_range : typing.Optional[typing.Iterable[global___DescriptorProto.ExtensionRange]] = ...,
        oneof_decl : typing.Optional[typing.Iterable[global___OneofDescriptorProto]] = ...,
        options : typing.Optional[global___MessageOptions] = ...,
        reserved_range : typing.Optional[typing.Iterable[global___DescriptorProto.ReservedRange]] = ...,
        reserved_name : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"enum_type",b"enum_type",u"extension",b"extension",u"extension_range",b"extension_range",u"field",b"field",u"name",b"name",u"nested_type",b"nested_type",u"oneof_decl",b"oneof_decl",u"options",b"options",u"reserved_name",b"reserved_name",u"reserved_range",b"reserved_range"]) -> None: ...
global___DescriptorProto = DescriptorProto

class ExtensionRangeOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___ExtensionRangeOptions = ExtensionRangeOptions

class FieldDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Type(metaclass=_Type):
        V = typing.NewType('V', builtins.int)

    TYPE_DOUBLE = FieldDescriptorProto.Type.V(1)
    TYPE_FLOAT = FieldDescriptorProto.Type.V(2)
    TYPE_INT64 = FieldDescriptorProto.Type.V(3)
    TYPE_UINT64 = FieldDescriptorProto.Type.V(4)
    TYPE_INT32 = FieldDescriptorProto.Type.V(5)
    TYPE_FIXED64 = FieldDescriptorProto.Type.V(6)
    TYPE_FIXED32 = FieldDescriptorProto.Type.V(7)
    TYPE_BOOL = FieldDescriptorProto.Type.V(8)
    TYPE_STRING = FieldDescriptorProto.Type.V(9)
    TYPE_GROUP = FieldDescriptorProto.Type.V(10)
    TYPE_MESSAGE = FieldDescriptorProto.Type.V(11)
    TYPE_BYTES = FieldDescriptorProto.Type.V(12)
    TYPE_UINT32 = FieldDescriptorProto.Type.V(13)
    TYPE_ENUM = FieldDescriptorProto.Type.V(14)
    TYPE_SFIXED32 = FieldDescriptorProto.Type.V(15)
    TYPE_SFIXED64 = FieldDescriptorProto.Type.V(16)
    TYPE_SINT32 = FieldDescriptorProto.Type.V(17)
    TYPE_SINT64 = FieldDescriptorProto.Type.V(18)

    class _Type(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Type.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        TYPE_DOUBLE = FieldDescriptorProto.Type.V(1)
        TYPE_FLOAT = FieldDescriptorProto.Type.V(2)
        TYPE_INT64 = FieldDescriptorProto.Type.V(3)
        TYPE_UINT64 = FieldDescriptorProto.Type.V(4)
        TYPE_INT32 = FieldDescriptorProto.Type.V(5)
        TYPE_FIXED64 = FieldDescriptorProto.Type.V(6)
        TYPE_FIXED32 = FieldDescriptorProto.Type.V(7)
        TYPE_BOOL = FieldDescriptorProto.Type.V(8)
        TYPE_STRING = FieldDescriptorProto.Type.V(9)
        TYPE_GROUP = FieldDescriptorProto.Type.V(10)
        TYPE_MESSAGE = FieldDescriptorProto.Type.V(11)
        TYPE_BYTES = FieldDescriptorProto.Type.V(12)
        TYPE_UINT32 = FieldDescriptorProto.Type.V(13)
        TYPE_ENUM = FieldDescriptorProto.Type.V(14)
        TYPE_SFIXED32 = FieldDescriptorProto.Type.V(15)
        TYPE_SFIXED64 = FieldDescriptorProto.Type.V(16)
        TYPE_SINT32 = FieldDescriptorProto.Type.V(17)
        TYPE_SINT64 = FieldDescriptorProto.Type.V(18)

    class Label(metaclass=_Label):
        V = typing.NewType('V', builtins.int)

    LABEL_OPTIONAL = FieldDescriptorProto.Label.V(1)
    LABEL_REQUIRED = FieldDescriptorProto.Label.V(2)
    LABEL_REPEATED = FieldDescriptorProto.Label.V(3)

    class _Label(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Label.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LABEL_OPTIONAL = FieldDescriptorProto.Label.V(1)
        LABEL_REQUIRED = FieldDescriptorProto.Label.V(2)
        LABEL_REPEATED = FieldDescriptorProto.Label.V(3)

    NAME_FIELD_NUMBER: builtins.int
    NUMBER_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TYPE_NAME_FIELD_NUMBER: builtins.int
    EXTENDEE_FIELD_NUMBER: builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: builtins.int
    ONEOF_INDEX_FIELD_NUMBER: builtins.int
    JSON_NAME_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    PROTO3_OPTIONAL_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    number: builtins.int = ...
    label: global___FieldDescriptorProto.Label.V = ...
    type: global___FieldDescriptorProto.Type.V = ...
    type_name: typing.Text = ...
    extendee: typing.Text = ...
    default_value: typing.Text = ...
    oneof_index: builtins.int = ...
    json_name: typing.Text = ...
    proto3_optional: builtins.bool = ...

    @property
    def options(self) -> global___FieldOptions: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        number : typing.Optional[builtins.int] = ...,
        label : typing.Optional[global___FieldDescriptorProto.Label.V] = ...,
        type : typing.Optional[global___FieldDescriptorProto.Type.V] = ...,
        type_name : typing.Optional[typing.Text] = ...,
        extendee : typing.Optional[typing.Text] = ...,
        default_value : typing.Optional[typing.Text] = ...,
        oneof_index : typing.Optional[builtins.int] = ...,
        json_name : typing.Optional[typing.Text] = ...,
        options : typing.Optional[global___FieldOptions] = ...,
        proto3_optional : typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"default_value",b"default_value",u"extendee",b"extendee",u"json_name",b"json_name",u"label",b"label",u"name",b"name",u"number",b"number",u"oneof_index",b"oneof_index",u"options",b"options",u"proto3_optional",b"proto3_optional",u"type",b"type",u"type_name",b"type_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"default_value",b"default_value",u"extendee",b"extendee",u"json_name",b"json_name",u"label",b"label",u"name",b"name",u"number",b"number",u"oneof_index",b"oneof_index",u"options",b"options",u"proto3_optional",b"proto3_optional",u"type",b"type",u"type_name",b"type_name"]) -> None: ...
global___FieldDescriptorProto = FieldDescriptorProto

class OneofDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def options(self) -> global___OneofOptions: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        options : typing.Optional[global___OneofOptions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options"]) -> None: ...
global___OneofDescriptorProto = OneofDescriptorProto

class EnumDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class EnumReservedRange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        start: builtins.int = ...
        end: builtins.int = ...

        def __init__(self,
            *,
            start : typing.Optional[builtins.int] = ...,
            end : typing.Optional[builtins.int] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"end",b"end",u"start",b"start"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"end",b"end",u"start",b"start"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    RESERVED_RANGE_FIELD_NUMBER: builtins.int
    RESERVED_NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def reserved_name(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...

    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnumValueDescriptorProto]: ...

    @property
    def options(self) -> global___EnumOptions: ...

    @property
    def reserved_range(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnumDescriptorProto.EnumReservedRange]: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        value : typing.Optional[typing.Iterable[global___EnumValueDescriptorProto]] = ...,
        options : typing.Optional[global___EnumOptions] = ...,
        reserved_range : typing.Optional[typing.Iterable[global___EnumDescriptorProto.EnumReservedRange]] = ...,
        reserved_name : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options",u"reserved_name",b"reserved_name",u"reserved_range",b"reserved_range",u"value",b"value"]) -> None: ...
global___EnumDescriptorProto = EnumDescriptorProto

class EnumValueDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    NUMBER_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    number: builtins.int = ...

    @property
    def options(self) -> global___EnumValueOptions: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        number : typing.Optional[builtins.int] = ...,
        options : typing.Optional[global___EnumValueOptions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"number",b"number",u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"number",b"number",u"options",b"options"]) -> None: ...
global___EnumValueDescriptorProto = EnumValueDescriptorProto

class ServiceDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def method(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MethodDescriptorProto]: ...

    @property
    def options(self) -> global___ServiceOptions: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        method : typing.Optional[typing.Iterable[global___MethodDescriptorProto]] = ...,
        options : typing.Optional[global___ServiceOptions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"method",b"method",u"name",b"name",u"options",b"options"]) -> None: ...
global___ServiceDescriptorProto = ServiceDescriptorProto

class MethodDescriptorProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    INPUT_TYPE_FIELD_NUMBER: builtins.int
    OUTPUT_TYPE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    CLIENT_STREAMING_FIELD_NUMBER: builtins.int
    SERVER_STREAMING_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    input_type: typing.Text = ...
    output_type: typing.Text = ...
    client_streaming: builtins.bool = ...
    server_streaming: builtins.bool = ...

    @property
    def options(self) -> global___MethodOptions: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Text] = ...,
        input_type : typing.Optional[typing.Text] = ...,
        output_type : typing.Optional[typing.Text] = ...,
        options : typing.Optional[global___MethodOptions] = ...,
        client_streaming : typing.Optional[builtins.bool] = ...,
        server_streaming : typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"client_streaming",b"client_streaming",u"input_type",b"input_type",u"name",b"name",u"options",b"options",u"output_type",b"output_type",u"server_streaming",b"server_streaming"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"client_streaming",b"client_streaming",u"input_type",b"input_type",u"name",b"name",u"options",b"options",u"output_type",b"output_type",u"server_streaming",b"server_streaming"]) -> None: ...
global___MethodDescriptorProto = MethodDescriptorProto

class FileOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class OptimizeMode(metaclass=_OptimizeMode):
        V = typing.NewType('V', builtins.int)

    SPEED = FileOptions.OptimizeMode.V(1)
    CODE_SIZE = FileOptions.OptimizeMode.V(2)
    LITE_RUNTIME = FileOptions.OptimizeMode.V(3)

    class _OptimizeMode(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OptimizeMode.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        SPEED = FileOptions.OptimizeMode.V(1)
        CODE_SIZE = FileOptions.OptimizeMode.V(2)
        LITE_RUNTIME = FileOptions.OptimizeMode.V(3)

    JAVA_PACKAGE_FIELD_NUMBER: builtins.int
    JAVA_OUTER_CLASSNAME_FIELD_NUMBER: builtins.int
    JAVA_MULTIPLE_FILES_FIELD_NUMBER: builtins.int
    JAVA_GENERATE_EQUALS_AND_HASH_FIELD_NUMBER: builtins.int
    JAVA_STRING_CHECK_UTF8_FIELD_NUMBER: builtins.int
    OPTIMIZE_FOR_FIELD_NUMBER: builtins.int
    GO_PACKAGE_FIELD_NUMBER: builtins.int
    CC_GENERIC_SERVICES_FIELD_NUMBER: builtins.int
    JAVA_GENERIC_SERVICES_FIELD_NUMBER: builtins.int
    PY_GENERIC_SERVICES_FIELD_NUMBER: builtins.int
    PHP_GENERIC_SERVICES_FIELD_NUMBER: builtins.int
    DEPRECATED_FIELD_NUMBER: builtins.int
    CC_ENABLE_ARENAS_FIELD_NUMBER: builtins.int
    OBJC_CLASS_PREFIX_FIELD_NUMBER: builtins.int
    CSHARP_NAMESPACE_FIELD_NUMBER: builtins.int
    SWIFT_PREFIX_FIELD_NUMBER: builtins.int
    PHP_CLASS_PREFIX_FIELD_NUMBER: builtins.int
    PHP_NAMESPACE_FIELD_NUMBER: builtins.int
    PHP_METADATA_NAMESPACE_FIELD_NUMBER: builtins.int
    RUBY_PACKAGE_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    java_package: typing.Text = ...
    java_outer_classname: typing.Text = ...
    java_multiple_files: builtins.bool = ...
    java_generate_equals_and_hash: builtins.bool = ...
    java_string_check_utf8: builtins.bool = ...
    optimize_for: global___FileOptions.OptimizeMode.V = ...
    go_package: typing.Text = ...
    cc_generic_services: builtins.bool = ...
    java_generic_services: builtins.bool = ...
    py_generic_services: builtins.bool = ...
    php_generic_services: builtins.bool = ...
    deprecated: builtins.bool = ...
    cc_enable_arenas: builtins.bool = ...
    objc_class_prefix: typing.Text = ...
    csharp_namespace: typing.Text = ...
    swift_prefix: typing.Text = ...
    php_class_prefix: typing.Text = ...
    php_namespace: typing.Text = ...
    php_metadata_namespace: typing.Text = ...
    ruby_package: typing.Text = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        java_package : typing.Optional[typing.Text] = ...,
        java_outer_classname : typing.Optional[typing.Text] = ...,
        java_multiple_files : typing.Optional[builtins.bool] = ...,
        java_generate_equals_and_hash : typing.Optional[builtins.bool] = ...,
        java_string_check_utf8 : typing.Optional[builtins.bool] = ...,
        optimize_for : typing.Optional[global___FileOptions.OptimizeMode.V] = ...,
        go_package : typing.Optional[typing.Text] = ...,
        cc_generic_services : typing.Optional[builtins.bool] = ...,
        java_generic_services : typing.Optional[builtins.bool] = ...,
        py_generic_services : typing.Optional[builtins.bool] = ...,
        php_generic_services : typing.Optional[builtins.bool] = ...,
        deprecated : typing.Optional[builtins.bool] = ...,
        cc_enable_arenas : typing.Optional[builtins.bool] = ...,
        objc_class_prefix : typing.Optional[typing.Text] = ...,
        csharp_namespace : typing.Optional[typing.Text] = ...,
        swift_prefix : typing.Optional[typing.Text] = ...,
        php_class_prefix : typing.Optional[typing.Text] = ...,
        php_namespace : typing.Optional[typing.Text] = ...,
        php_metadata_namespace : typing.Optional[typing.Text] = ...,
        ruby_package : typing.Optional[typing.Text] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"cc_enable_arenas",b"cc_enable_arenas",u"cc_generic_services",b"cc_generic_services",u"csharp_namespace",b"csharp_namespace",u"deprecated",b"deprecated",u"go_package",b"go_package",u"java_generate_equals_and_hash",b"java_generate_equals_and_hash",u"java_generic_services",b"java_generic_services",u"java_multiple_files",b"java_multiple_files",u"java_outer_classname",b"java_outer_classname",u"java_package",b"java_package",u"java_string_check_utf8",b"java_string_check_utf8",u"objc_class_prefix",b"objc_class_prefix",u"optimize_for",b"optimize_for",u"php_class_prefix",b"php_class_prefix",u"php_generic_services",b"php_generic_services",u"php_metadata_namespace",b"php_metadata_namespace",u"php_namespace",b"php_namespace",u"py_generic_services",b"py_generic_services",u"ruby_package",b"ruby_package",u"swift_prefix",b"swift_prefix"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cc_enable_arenas",b"cc_enable_arenas",u"cc_generic_services",b"cc_generic_services",u"csharp_namespace",b"csharp_namespace",u"deprecated",b"deprecated",u"go_package",b"go_package",u"java_generate_equals_and_hash",b"java_generate_equals_and_hash",u"java_generic_services",b"java_generic_services",u"java_multiple_files",b"java_multiple_files",u"java_outer_classname",b"java_outer_classname",u"java_package",b"java_package",u"java_string_check_utf8",b"java_string_check_utf8",u"objc_class_prefix",b"objc_class_prefix",u"optimize_for",b"optimize_for",u"php_class_prefix",b"php_class_prefix",u"php_generic_services",b"php_generic_services",u"php_metadata_namespace",b"php_metadata_namespace",u"php_namespace",b"php_namespace",u"py_generic_services",b"py_generic_services",u"ruby_package",b"ruby_package",u"swift_prefix",b"swift_prefix",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___FileOptions = FileOptions

class MessageOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_SET_WIRE_FORMAT_FIELD_NUMBER: builtins.int
    NO_STANDARD_DESCRIPTOR_ACCESSOR_FIELD_NUMBER: builtins.int
    DEPRECATED_FIELD_NUMBER: builtins.int
    MAP_ENTRY_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    message_set_wire_format: builtins.bool = ...
    no_standard_descriptor_accessor: builtins.bool = ...
    deprecated: builtins.bool = ...
    map_entry: builtins.bool = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        message_set_wire_format : typing.Optional[builtins.bool] = ...,
        no_standard_descriptor_accessor : typing.Optional[builtins.bool] = ...,
        deprecated : typing.Optional[builtins.bool] = ...,
        map_entry : typing.Optional[builtins.bool] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"map_entry",b"map_entry",u"message_set_wire_format",b"message_set_wire_format",u"no_standard_descriptor_accessor",b"no_standard_descriptor_accessor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"map_entry",b"map_entry",u"message_set_wire_format",b"message_set_wire_format",u"no_standard_descriptor_accessor",b"no_standard_descriptor_accessor",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___MessageOptions = MessageOptions

class FieldOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class CType(metaclass=_CType):
        V = typing.NewType('V', builtins.int)

    STRING = FieldOptions.CType.V(0)
    CORD = FieldOptions.CType.V(1)
    STRING_PIECE = FieldOptions.CType.V(2)

    class _CType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        STRING = FieldOptions.CType.V(0)
        CORD = FieldOptions.CType.V(1)
        STRING_PIECE = FieldOptions.CType.V(2)

    class JSType(metaclass=_JSType):
        V = typing.NewType('V', builtins.int)

    JS_NORMAL = FieldOptions.JSType.V(0)
    JS_STRING = FieldOptions.JSType.V(1)
    JS_NUMBER = FieldOptions.JSType.V(2)

    class _JSType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[JSType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        JS_NORMAL = FieldOptions.JSType.V(0)
        JS_STRING = FieldOptions.JSType.V(1)
        JS_NUMBER = FieldOptions.JSType.V(2)

    CTYPE_FIELD_NUMBER: builtins.int
    PACKED_FIELD_NUMBER: builtins.int
    JSTYPE_FIELD_NUMBER: builtins.int
    LAZY_FIELD_NUMBER: builtins.int
    DEPRECATED_FIELD_NUMBER: builtins.int
    WEAK_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    ctype: global___FieldOptions.CType.V = ...
    packed: builtins.bool = ...
    jstype: global___FieldOptions.JSType.V = ...
    lazy: builtins.bool = ...
    deprecated: builtins.bool = ...
    weak: builtins.bool = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        ctype : typing.Optional[global___FieldOptions.CType.V] = ...,
        packed : typing.Optional[builtins.bool] = ...,
        jstype : typing.Optional[global___FieldOptions.JSType.V] = ...,
        lazy : typing.Optional[builtins.bool] = ...,
        deprecated : typing.Optional[builtins.bool] = ...,
        weak : typing.Optional[builtins.bool] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ctype",b"ctype",u"deprecated",b"deprecated",u"jstype",b"jstype",u"lazy",b"lazy",u"packed",b"packed",u"weak",b"weak"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ctype",b"ctype",u"deprecated",b"deprecated",u"jstype",b"jstype",u"lazy",b"lazy",u"packed",b"packed",u"uninterpreted_option",b"uninterpreted_option",u"weak",b"weak"]) -> None: ...
global___FieldOptions = FieldOptions

class OneofOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___OneofOptions = OneofOptions

class EnumOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALLOW_ALIAS_FIELD_NUMBER: builtins.int
    DEPRECATED_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    allow_alias: builtins.bool = ...
    deprecated: builtins.bool = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        allow_alias : typing.Optional[builtins.bool] = ...,
        deprecated : typing.Optional[builtins.bool] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"allow_alias",b"allow_alias",u"deprecated",b"deprecated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"allow_alias",b"allow_alias",u"deprecated",b"deprecated",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___EnumOptions = EnumOptions

class EnumValueOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEPRECATED_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    deprecated: builtins.bool = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        deprecated : typing.Optional[builtins.bool] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___EnumValueOptions = EnumValueOptions

class ServiceOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEPRECATED_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    deprecated: builtins.bool = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        deprecated : typing.Optional[builtins.bool] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___ServiceOptions = ServiceOptions

class MethodOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class IdempotencyLevel(metaclass=_IdempotencyLevel):
        V = typing.NewType('V', builtins.int)

    IDEMPOTENCY_UNKNOWN = MethodOptions.IdempotencyLevel.V(0)
    NO_SIDE_EFFECTS = MethodOptions.IdempotencyLevel.V(1)
    IDEMPOTENT = MethodOptions.IdempotencyLevel.V(2)

    class _IdempotencyLevel(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IdempotencyLevel.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        IDEMPOTENCY_UNKNOWN = MethodOptions.IdempotencyLevel.V(0)
        NO_SIDE_EFFECTS = MethodOptions.IdempotencyLevel.V(1)
        IDEMPOTENT = MethodOptions.IdempotencyLevel.V(2)

    DEPRECATED_FIELD_NUMBER: builtins.int
    IDEMPOTENCY_LEVEL_FIELD_NUMBER: builtins.int
    UNINTERPRETED_OPTION_FIELD_NUMBER: builtins.int
    deprecated: builtins.bool = ...
    idempotency_level: global___MethodOptions.IdempotencyLevel.V = ...

    @property
    def uninterpreted_option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption]: ...

    def __init__(self,
        *,
        deprecated : typing.Optional[builtins.bool] = ...,
        idempotency_level : typing.Optional[global___MethodOptions.IdempotencyLevel.V] = ...,
        uninterpreted_option : typing.Optional[typing.Iterable[global___UninterpretedOption]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"idempotency_level",b"idempotency_level"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deprecated",b"deprecated",u"idempotency_level",b"idempotency_level",u"uninterpreted_option",b"uninterpreted_option"]) -> None: ...
global___MethodOptions = MethodOptions

class UninterpretedOption(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class NamePart(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        NAME_PART_FIELD_NUMBER: builtins.int
        IS_EXTENSION_FIELD_NUMBER: builtins.int
        name_part: typing.Text = ...
        is_extension: builtins.bool = ...

        def __init__(self,
            *,
            name_part : typing.Optional[typing.Text] = ...,
            is_extension : typing.Optional[builtins.bool] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"is_extension",b"is_extension",u"name_part",b"name_part"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"is_extension",b"is_extension",u"name_part",b"name_part"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    IDENTIFIER_VALUE_FIELD_NUMBER: builtins.int
    POSITIVE_INT_VALUE_FIELD_NUMBER: builtins.int
    NEGATIVE_INT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    AGGREGATE_VALUE_FIELD_NUMBER: builtins.int
    identifier_value: typing.Text = ...
    positive_int_value: builtins.int = ...
    negative_int_value: builtins.int = ...
    double_value: builtins.float = ...
    string_value: builtins.bytes = ...
    aggregate_value: typing.Text = ...

    @property
    def name(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UninterpretedOption.NamePart]: ...

    def __init__(self,
        *,
        name : typing.Optional[typing.Iterable[global___UninterpretedOption.NamePart]] = ...,
        identifier_value : typing.Optional[typing.Text] = ...,
        positive_int_value : typing.Optional[builtins.int] = ...,
        negative_int_value : typing.Optional[builtins.int] = ...,
        double_value : typing.Optional[builtins.float] = ...,
        string_value : typing.Optional[builtins.bytes] = ...,
        aggregate_value : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"aggregate_value",b"aggregate_value",u"double_value",b"double_value",u"identifier_value",b"identifier_value",u"negative_int_value",b"negative_int_value",u"positive_int_value",b"positive_int_value",u"string_value",b"string_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aggregate_value",b"aggregate_value",u"double_value",b"double_value",u"identifier_value",b"identifier_value",u"name",b"name",u"negative_int_value",b"negative_int_value",u"positive_int_value",b"positive_int_value",u"string_value",b"string_value"]) -> None: ...
global___UninterpretedOption = UninterpretedOption

class SourceCodeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Location(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        PATH_FIELD_NUMBER: builtins.int
        SPAN_FIELD_NUMBER: builtins.int
        LEADING_COMMENTS_FIELD_NUMBER: builtins.int
        TRAILING_COMMENTS_FIELD_NUMBER: builtins.int
        LEADING_DETACHED_COMMENTS_FIELD_NUMBER: builtins.int

        @property
        def path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...

        @property
        def span(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        leading_comments: typing.Text = ...
        trailing_comments: typing.Text = ...

        @property
        def leading_detached_comments(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...

        def __init__(self,
            *,
            path : typing.Optional[typing.Iterable[builtins.int]] = ...,
            span : typing.Optional[typing.Iterable[builtins.int]] = ...,
            leading_comments : typing.Optional[typing.Text] = ...,
            trailing_comments : typing.Optional[typing.Text] = ...,
            leading_detached_comments : typing.Optional[typing.Iterable[typing.Text]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"leading_comments",b"leading_comments",u"trailing_comments",b"trailing_comments"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"leading_comments",b"leading_comments",u"leading_detached_comments",b"leading_detached_comments",u"path",b"path",u"span",b"span",u"trailing_comments",b"trailing_comments"]) -> None: ...

    LOCATION_FIELD_NUMBER: builtins.int

    @property
    def location(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SourceCodeInfo.Location]: ...

    def __init__(self,
        *,
        location : typing.Optional[typing.Iterable[global___SourceCodeInfo.Location]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"location",b"location"]) -> None: ...
global___SourceCodeInfo = SourceCodeInfo

class GeneratedCodeInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Annotation(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        PATH_FIELD_NUMBER: builtins.int
        SOURCE_FILE_FIELD_NUMBER: builtins.int
        BEGIN_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int

        @property
        def path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        source_file: typing.Text = ...
        begin: builtins.int = ...
        end: builtins.int = ...

        def __init__(self,
            *,
            path : typing.Optional[typing.Iterable[builtins.int]] = ...,
            source_file : typing.Optional[typing.Text] = ...,
            begin : typing.Optional[builtins.int] = ...,
            end : typing.Optional[builtins.int] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"begin",b"begin",u"end",b"end",u"source_file",b"source_file"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"begin",b"begin",u"end",b"end",u"path",b"path",u"source_file",b"source_file"]) -> None: ...

    ANNOTATION_FIELD_NUMBER: builtins.int

    @property
    def annotation(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeneratedCodeInfo.Annotation]: ...

    def __init__(self,
        *,
        annotation : typing.Optional[typing.Iterable[global___GeneratedCodeInfo.Annotation]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"annotation",b"annotation"]) -> None: ...
global___GeneratedCodeInfo = GeneratedCodeInfo
