"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.well_known_types
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Duration(google.protobuf.message.Message, google.protobuf.internal.well_known_types.Duration):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int = ...
    nanos: builtins.int = ...

    def __init__(self,
        *,
        seconds : builtins.int = ...,
        nanos : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"nanos",b"nanos",u"seconds",b"seconds"]) -> None: ...
global___Duration = Duration
