from Xlib.display import Display
from Xlib.error import XError
from Xlib.protocol import request, rq
from Xlib.xobject import resource

extname: str
DamageNotifyCode: int
BadDamageCode: int

class BadDamageError(XError): ...

DamageReportRawRectangles: int
DamageReportDeltaRectangles: int
DamageReportBoundingBox: int
DamageReportNonEmpty: int
DamageReportLevel: tuple[int, int, int, int]
DAMAGE = rq.Card32

class QueryVersion(rq.ReplyRequest): ...

def query_version(self: Display | resource.Resource) -> QueryVersion: ...

class DamageCreate(rq.Request): ...

def damage_create(self: Display | resource.Resource, level: int) -> int: ...

class DamageDestroy(rq.Request): ...

def damage_destroy(self: Display | resource.Resource, damage: int) -> None: ...

class DamageSubtract(rq.Request): ...

def damage_subtract(self: Display | resource.Resource, damage: int, repair: int = ..., parts: int = ...) -> None: ...

class DamageAdd(rq.Request): ...

def damage_add(self: Display | resource.Resource, repair: int, parts: int) -> None: ...

class DamageNotify(rq.Event): ...

def init(disp: Display, info: request.QueryExtension) -> None: ...
