from _typeshed import Incomplete

import arrow

class DateMathException(Exception): ...

def parse(
    expression: str, now: arrow.Arrow | None = ..., tz: str = ..., type: str | None = ..., roundDown: bool = ...
) -> arrow.Arrow: ...
def __getattr__(name: str) -> Incomplete: ...
