from _typeshed import Incomplete

def categorical_node_match(attr, default): ...

categorical_edge_match: Incomplete

def categorical_multiedge_match(attr, default): ...
def numerical_node_match(attr, default, rtol: float = 1e-05, atol: float = 1e-08): ...

numerical_edge_match: Incomplete

def numerical_multiedge_match(attr, default, rtol: float = 1e-05, atol: float = 1e-08): ...
def generic_node_match(attr, default, op): ...

generic_edge_match: Incomplete

def generic_multiedge_match(attr, default, op): ...
