from _typeshed import Incomplete

def full_rary_tree(r, n, create_using: Incomplete | None = None): ...
def balanced_tree(r, h, create_using: Incomplete | None = None): ...
def barbell_graph(m1, m2, create_using: Incomplete | None = None): ...
def binomial_tree(n, create_using: Incomplete | None = None): ...
def complete_graph(n, create_using: Incomplete | None = None): ...
def circular_ladder_graph(n, create_using: Incomplete | None = None): ...
def circulant_graph(n, offsets, create_using: Incomplete | None = None): ...
def cycle_graph(n, create_using: Incomplete | None = None): ...
def dorogovtsev_goltsev_mendes_graph(n, create_using: Incomplete | None = None): ...
def empty_graph(n: Incomplete | int = 0, create_using: Incomplete | None = None, default=...): ...
def ladder_graph(n, create_using: Incomplete | None = None): ...
def lollipop_graph(m, n, create_using: Incomplete | None = None): ...
def null_graph(create_using: Incomplete | None = None): ...
def path_graph(n, create_using: Incomplete | None = None): ...
def star_graph(n, create_using: Incomplete | None = None): ...
def trivial_graph(create_using: Incomplete | None = None): ...
def turan_graph(n, r): ...
def wheel_graph(n, create_using: Incomplete | None = None): ...
def complete_multipartite_graph(*subset_sizes): ...
