from _typeshed import Incomplete

def LCF_graph(n, shift_list, repeats, create_using: Incomplete | None = None): ...
def bull_graph(create_using: Incomplete | None = None): ...
def chvatal_graph(create_using: Incomplete | None = None): ...
def cubical_graph(create_using: Incomplete | None = None): ...
def desargues_graph(create_using: Incomplete | None = None): ...
def diamond_graph(create_using: Incomplete | None = None): ...
def dodecahedral_graph(create_using: Incomplete | None = None): ...
def frucht_graph(create_using: Incomplete | None = None): ...
def heawood_graph(create_using: Incomplete | None = None): ...
def hoffman_singleton_graph(): ...
def house_graph(create_using: Incomplete | None = None): ...
def house_x_graph(create_using: Incomplete | None = None): ...
def icosahedral_graph(create_using: Incomplete | None = None): ...
def krackhardt_kite_graph(create_using: Incomplete | None = None): ...
def moebius_kantor_graph(create_using: Incomplete | None = None): ...
def octahedral_graph(create_using: Incomplete | None = None): ...
def pappus_graph(): ...
def petersen_graph(create_using: Incomplete | None = None): ...
def sedgewick_maze_graph(create_using: Incomplete | None = None): ...
def tetrahedral_graph(create_using: Incomplete | None = None): ...
def truncated_cube_graph(create_using: Incomplete | None = None): ...
def truncated_tetrahedron_graph(create_using: Incomplete | None = None): ...
def tutte_graph(create_using: Incomplete | None = None): ...
