from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def LCF_graph(n, shift_list, repeats, create_using: Incomplete | None = None): ...
@_dispatchable
def bull_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def chvatal_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def cubical_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def desargues_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def diamond_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def dodecahedral_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def frucht_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def heawood_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def hoffman_singleton_graph(): ...
@_dispatchable
def house_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def house_x_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def icosahedral_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def krackhardt_kite_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def moebius_kantor_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def octahedral_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def pappus_graph(): ...
@_dispatchable
def petersen_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def sedgewick_maze_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def tetrahedral_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def truncated_cube_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def truncated_tetrahedron_graph(create_using: Incomplete | None = None): ...
@_dispatchable
def tutte_graph(create_using: Incomplete | None = None): ...
