from networkx.utils.backends import _dispatchable

@_dispatchable
def karate_club_graph(): ...
@_dispatchable
def davis_southern_women_graph(): ...
@_dispatchable
def florentine_families_graph(): ...
@_dispatchable
def les_miserables_graph(): ...
