version = "1.3.*"
upstream_repository = "https://github.com/python-caldav/caldav"
# also types-lxml and types-icalendar when those stubs are added
requires = ["types-requests", "types-vobject"]
partial_stub = true
obsolete_since = "1.4.0" # Released on 2024-11-05

[tool.stubtest]
ignore_missing_stub = true
