/// <reference path="fourslash.ts" />

// @filename: pyrightconfig.json
//// {
////   "reportMissingTypeStubs": "warning"
//// }

// @filename: testLib/__init__.py
// @library: true
//// # This is a library file
//// from typing import Callable
//// class MyLibrary:
////     def DoEveryThing(self, func: Callable[..., float]):
////         return func

// @filename: test.py
//// import [|/*marker*/testLi|]b

// @ts-ignore
await helper.verifyInvokeCodeAction({
    marker: {
        title: `Create Type Stub For "testLib"`,
        files: {
            ['/typings/testLib/__init__.pyi']: `"""
This type stub file was generated by pyright.
"""

from typing import Callable

class MyLibrary:
    def DoEveryThing(self, func: Callable[..., float]): # -> Callable[..., float]:
        ...
    


`,
        },
    },
});
