from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def laplacian_spectrum(G, weight: str = "weight"): ...
@_dispatchable
def normalized_laplacian_spectrum(G, weight: str = "weight"): ...
@_dispatchable
def adjacency_spectrum(G, weight: str = "weight"): ...
@_dispatchable
def modularity_spectrum(G): ...
@_dispatchable
def bethe_hessian_spectrum(G, r: Incomplete | None = None): ...
