from typing import Any
import asyncio

futures: Any

class ReturnValueIgnoredError(Exception): ...

class _TracebackLogger:
    exc_info: Any
    formatted_tb: Any
    def __init__(self, exc_info) -> None: ...
    def activate(self): ...
    def clear(self): ...
    def __del__(self): ...

Future = asyncio.Future

TracebackFuture: Any
FUTURES: Any

def is_future(x): ...

class DummyExecutor:
    def submit(self, fn, *args, **kwargs): ...
    def shutdown(self, wait=...): ...

dummy_executor: Any

def run_on_executor(*args, **kwargs): ...
def return_future(f): ...
def chain_future(a, b): ...
