version = "1.3.*"
stub_distribution = "types-pika-ts"  # https://github.com/python/typeshed/issues/9246
extra_description = """\
The `types-pika` package contains alternate, more complete type stubs, that \
are maintained outside of typeshed.\
"""

[tool.stubtest]
ignore_missing_stub = false
