version = "2.0.*"
# Requires a version of numpy with a `py.typed` file
# see https://github.com/python/typeshed/issues/12551
# on why we need the upper bound for numpy
requires = ["numpy>=1.20,<2.1.0"]
upstream_repository = "https://github.com/shapely/shapely"
