version = "10.0.*"
upstream_repository = "https://github.com/python-pillow/Pillow"
partial_stub = true

[tool.stubtest]
stubtest_requirements = ["olefile"]
# darwin checks don't affect stubtest
platforms = ["linux", "win32"]
