from _typeshed import Incomplete
from typing import Any

MAX_ATTEMPTS: int
logger: Any

def prompt_for_confirmation(question, default: Incomplete | None = ..., padding: bool = ...): ...
def prompt_for_choice(choices, default: Incomplete | None = ..., padding: bool = ...): ...
def prompt_for_input(question, default: Incomplete | None = ..., padding: bool = ..., strip: bool = ...): ...
def prepare_prompt_text(prompt_text, **options): ...
def prepare_friendly_prompts() -> None: ...
def retry_limit(limit=...) -> None: ...

class TooManyInvalidReplies(Exception): ...
