def HrInstallService() -> None: ...
def HrInstallMailboxAgent() -> None: ...
def HrCreateMailboxAgentProfile(serviceName: str, profile: str) -> None: ...
def HrCreateGatewayProfile(serviceName: str, profile: str) -> None: ...
def HrMailboxAgentExists(server: str, siteDN: str, rdn: str) -> None: ...
def HrAdminProgramExists() -> None: ...
def HrRemoveMailboxAgent(server: str, siteDN: str, rdn: str) -> None: ...
def HrRemoveProfile(profile: str) -> None: ...
def HrEnumOrganizations(rootDN: str, server: str) -> list[str]: ...
def HrEnumSites(server: str, organizationDN: str) -> list[str]: ...
def HrEnumContainers(server: str, siteDN: str, fSubtree) -> list[str]: ...
def HrEnumSiteAdmins(server: str, siteDN: str) -> list[str]: ...
def HrGetServiceAccountName(serviceName: str, serviceName1: str) -> str: ...
