from _typeshed import Incomplete
from typing import Any

import _win32typing

def __getattr__(name: str) -> Any: ...  # incomplete
def HrGetExchangeStatus(server: str) -> tuple[Incomplete, Incomplete]: ...
def HrGetMailboxDN(session) -> str: ...
def HrGetServerDN(session) -> str: ...
def HrMAPIFindDefaultMsgStore(session: _win32typing.PyIMAPISession) -> str: ...
def HrMAPIFindIPMSubtree(msgStore: _win32typing.PyIMsgStore) -> str: ...
def HrMAPIFindInbox(msgStore: _win32typing.PyIMsgStore) -> str: ...
def HrMAPIFindSubfolderEx(rootFolder: _win32typing.PyIMAPIFolder, sep: str, name: str) -> _win32typing.PyIMsgStore: ...
def HrMAPIFindFolder(folder: _win32typing.PyIMAPIFolder, name: str) -> str: ...
def HrMAPIFindFolderEx(msgStore: _win32typing.PyIMsgStore, sepString: str, path: str) -> str: ...
def HrMAPIFindStore(session: _win32typing.PyIMAPISession, name: str) -> _win32typing.PyIMsgStore: ...
def HrCreateProfileName(profPrefix: str) -> str: ...
def HrCreateDirEntryIdEx(addrBook: _win32typing.PyIAddrBook, distinguishedName: str) -> str: ...
def HrFindExchangeGlobalAddresslist(addrBook: _win32typing.PyIAddrBook) -> str: ...
def HrMailboxLogon(
    session: _win32typing.PyIMAPISession, msgStore: _win32typing.PyIMsgStore, msgStoreDN: str, mailboxDN: str
) -> _win32typing.PyIMsgStore: ...
def HrMailboxLogoff(inbox: _win32typing.PyIMsgStore) -> None: ...
def HrMAPIOpenFolderEx(msgStore: _win32typing.PyIMsgStore, sep: str, name: str) -> _win32typing.PyIMAPIFolder: ...
def HrMAPISetPropBoolean(obj: _win32typing.PyIMAPIProp, tag) -> None: ...
def HrMAPISetPropLong(obj: _win32typing.PyIMAPIProp, tag) -> None: ...
def HrOpenExchangePublicStore(session: _win32typing.PyIMAPISession) -> _win32typing.PyIMsgStore: ...
def HrOpenExchangePrivateStore(session: _win32typing.PyIMAPISession) -> _win32typing.PyIMsgStore: ...
def HrOpenExchangePublicFolders(store: _win32typing.PyIMsgStore) -> _win32typing.PyIMAPIFolder: ...
def HrOpenSessionObject(session: _win32typing.PyIMAPISession) -> _win32typing.PyIMAPIProp: ...
def HrOpenSiteContainer(session: _win32typing.PyIMAPISession) -> _win32typing.PyIMAPIProp: ...
def HrOpenSiteContainerAddressing(session: _win32typing.PyIMAPISession) -> _win32typing.PyIMAPIProp: ...

OPENSTORE_HOME_LOGON: int
OPENSTORE_OVERRIDE_HOME_MDB: int
OPENSTORE_PUBLIC: int
OPENSTORE_TAKE_OWNERSHIP: int
OPENSTORE_USE_ADMIN_PRIVILEGE: int
IID_IExchangeManageStore: _win32typing.PyIID
IID_IExchangeManageStoreEx: _win32typing.PyIID
