from _typeshed import Incomplete

from networkx.utils.backends import _dispatchable

@_dispatchable
def color(G): ...
@_dispatchable
def is_bipartite(G): ...
@_dispatchable
def is_bipartite_node_set(G, nodes): ...
@_dispatchable
def sets(G, top_nodes: Incomplete | None = None): ...
@_dispatchable
def density(B, nodes): ...
@_dispatchable
def degrees(B, nodes, weight: Incomplete | None = None): ...
