from _typeshed import Incomplete

def complete_bipartite_graph(n1, n2, create_using: Incomplete | None = None): ...
def configuration_model(aseq, bseq, create_using: Incomplete | None = None, seed: Incomplete | None = None): ...
def havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = None): ...
def reverse_havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = None): ...
def alternating_havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = None): ...
def preferential_attachment_graph(aseq, p, create_using: Incomplete | None = None, seed: Incomplete | None = None): ...
def random_graph(n, m, p, seed: Incomplete | None = None, directed: bool = False): ...
def gnmk_random_graph(n, m, k, seed: Incomplete | None = None, directed: bool = False): ...
