version = "69.1.*"
upstream_repository = "https://github.com/pypa/setuptools"

[tool.stubtest]
# darwin is equivalent to linux for OS-specific methods
platforms = ["linux", "win32"]
stubtest_requirements = ["tomli"]
