from _typeshed import Incomplete

# Necessary for mypy to not throw AssertionError with win32com.client
class CDispatch:
    def __init__(
        self,
        IDispatch,
        olerepr,
        userName: Incomplete | None = ...,
        UnicodeToString: Incomplete | None = ...,
        lazydata: Incomplete | None = ...,
    ) -> None: ...
    def __call__(self, *args): ...
    def __bool__(self): ...
    def __dir__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __int__(self): ...
    def __len__(self): ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, *args): ...
    def __LazyMap__(self, attr): ...
    def __AttrToID__(self, attr): ...
    ob: Incomplete
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None: ...
