def get_official_languages(territory: str, regional: bool = False, de_facto: bool = False) -> tuple[str, ...]: ...
def get_territory_language_info(territory: str) -> dict[str, dict[str, float | str | None]]: ...
