def get_official_languages(territory: str, regional: bool = ..., de_facto: bool = ...) -> tuple[str, ...]: ...
def get_territory_language_info(territory: str) -> dict[str, dict[str, float | str | None]]: ...
