from _typeshed import Incomplete

def global_reaching_centrality(G, weight: Incomplete | None = None, normalized: bool = True): ...
def local_reaching_centrality(
    G, v, paths: Incomplete | None = None, weight: Incomplete | None = None, normalized: bool = True
): ...
