from networkx.utils.backends import _dispatchable

@_dispatchable
def trophic_levels(G, weight: str = "weight"): ...
@_dispatchable
def trophic_differences(G, weight: str = "weight"): ...
@_dispatchable
def trophic_incoherence_parameter(G, weight: str = "weight", cannibalism: bool = False): ...
