# This workflow runs mypy_primer, a tool that runs pyright on a variety
# of open-source Python projects that are known to type check with pyright.
# It builds pyright from the latest commit and the last release tag and
# compares the output of both. It uploads the diffs as an artifact.
name: Run mypy_primer on push

env:
  NODE_VERSION: '24.15.0' # Shipped with VS Code.

on:
  # Run on all pushes to main.
  push:
    branches:
      - main
    paths:
      - 'packages/pyright/**'
      - 'packages/pyright-internal/src/**'
      - 'packages/pyright-internal/typeshed-fallback/**'
  # Also run manually if requested.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mypy_primer:
    name: Run mypy_primer on push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: pyright_to_test
          fetch-depth: 0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          package_json_file: pyright_to_test/package.json
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pyright_to_test/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install git+https://github.com/hauntsaninja/mypy_primer.git
      - name: Run mypy_primer
        shell: bash
        env:
          # mypy_primer installs both the new and old commits. The old commit can contain
          # historical peer dependency conflicts that should not block primer comparisons.
          NPM_CONFIG_LEGACY_PEER_DEPS: 'true'
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
        run: |
          cd pyright_to_test
          echo "new commit"
          git rev-list --format=%s --max-count=1 $GITHUB_SHA

          cd ..
          npm config set legacy-peer-deps true --location=user
          npm config get legacy-peer-deps
          # fail action if exit code isn't zero or one
          (
            mypy_primer \
            --repo pyright_to_test \
            --type-checker pyright \
            --new $GITHUB_SHA \
            --debug \
            --output concise \
            | tee diff.txt
          ) || [ $? -eq 1 ]
      - name: Upload mypy_primer diff
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mypy_primer_diffs
          path: diff.txt
