name: 'Validation'

env:
  NODE_VERSION: '24.15.0' # Shipped with VS Code.
  PYTHON_VERSION: 3.11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  typecheck:
    if: github.repository == 'microsoft/pyright'
    runs-on: ubuntu-latest
    name: Typecheck

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - uses: ./.github/actions/choose-npm-install

      - run: pnpm exec lerna exec --stream --no-bail -- "tsc --noEmit"

  style:
    if: github.repository == 'microsoft/pyright'
    runs-on: ubuntu-latest
    name: Style

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - uses: ./.github/actions/choose-npm-install

      - name: Check diff after pnpm install
        run: git diff --exit-code --name-only

      - run: pnpm run check

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: typecheck

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - uses: ./.github/actions/choose-npm-install

      - name: pnpm test (pyright-internal)
        run: pnpm test
        working-directory: packages/pyright-internal

      # Install python so we can create a VENV for tests
      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        id: install_python
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Create Venv
        run: |
          ${{ steps.install_python.outputs.python-path }} -m venv .venv

      - name: Activate and install pytest (linux)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          python -m pip install pytest
          python -c "import sys;print('python_venv_path=' + sys.executable)" >> $GITHUB_ENV

      - name: Activate and install pytest (windows)
        if: runner.os == 'Windows'
        run: |
          .venv\scripts\activate
          python -m pip install pytest
          python -c "import sys;print('python_venv_path=' + sys.executable)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Echo python_venv_path
        run: |
          echo python_venv_path=${{env.python_venv_path}}

      - name: Run import tests with venv
        env:
          CI_IMPORT_TEST_VENVPATH: '../../'
          CI_IMPORT_TEST_VENV: '.venv'
        run: pnpm run test:imports
        working-directory: packages/pyright-internal

      - name: Run import tests with pythonpath
        env:
          CI_IMPORT_TEST_PYTHONPATH: ${{env.python_venv_path}}
        run: pnpm run test:imports
        working-directory: packages/pyright-internal

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: typecheck
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - uses: ./.github/actions/choose-npm-install

      - run: npm publish --dry-run
        working-directory: packages/pyright

      - run: npm publish --dry-run
        working-directory: packages/pyright-typeserver

      - run: pnpm run package
        working-directory: packages/vscode-pyright

  required:
    runs-on: ubuntu-latest
    name: Required
    needs:
      - typecheck
      - style
      - test
      - build

    steps:
      - run: echo All required jobs succeeded.
